services:
  - type: web
    name: code-editor
    env: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    port: 5513
